apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: clint-gateway
  name: clint-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clint-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clint-gateway
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/microservicios-nestjs/image-registry/client-gateway
          name: client-gateway
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources: {}
status: {}
